Part 7:  Ajax
neverovda/QnA pull request #8
Opened 2018-12-19 08:56 UTC by neverovda

2018-12-21 11:06 UTC, vkurennov requested changes

2018-12-21 11:06 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    answer.update(answer_params)
Не хватает проверки на авторство, запрос легко сделать напрямую, в обход интерфейса

2018-12-21 11:06 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    answer.check_best.save
Очень хрупкая конструкция. Можно забыть вызывать save и ответ не станет лучшим. Поэтому метод должен полностью менять состояние объекта. Т.е. вызвали метод - поменялось состояние и в памяти и в базе, больше ничего делать не нужно

2018-12-21 11:06 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  def update
Также не хватает проверки на авторство

2018-12-21 11:06 UTC, vkurennov commented on app/models/answer.rb
> +  def check_best
Весь метод можно записать в одну строку (не забывай о инверсии логических выражений): `self.best = !best`

2018-12-21 11:06 UTC, vkurennov commented on app/models/answer.rb
> +  def check_best
C учетом этого, стоит сделать не 2 метода, а один, который будет делать все, что нужно

2018-12-21 11:06 UTC, vkurennov commented on app/models/answer.rb
> +      best_answer.best = false
Используй update, чтобы установить значения и одновременно сохранить объект

2018-12-21 11:06 UTC, vkurennov commented on app/models/question.rb
> +  def sorted_answers
Прочитай (или посмотри в базовой части курса по рейлс) тему про скоупы

2018-12-21 11:06 UTC, vkurennov commented on app/views/answers/best.js.erb
> +currentAnswer = $('<%= ".answer_#{answer.id}" %>');
js-ответы должны быть краткими, в них не нужно возвращать функции. Функции стоит разместить статически в ассетах и здесь вызывать

2018-12-21 11:06 UTC, vkurennov commented on app/views/answers/update.js.erb
> +  $('.answers').html('<%= j render question.answers %>');
Обновлять нужно только тот ответ, который изменился, а не весь список

2018-12-21 11:06 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  = render 'questions/question_show'
попробуй применить аноанимные паршалы (назови паршл _question и тогда можно будет рендерить его как `render @question`)

2018-12-21 11:06 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +  describe 'PATCH #update' do
Тут еще должны быть контексты для автора и для не автора

2018-12-21 11:06 UTC, vkurennov commented on spec/features/answers/best_spec.rb
> +    scenario 'uncheck the best answer', js: true do
Не очень понятный тест. Дважды кликаем по одной и той же ссылке, получаем разные результаты. Так может, не нужно показывать ссылку, если ответ уже лучший? Тогда будет логично: у нелучших ответов ссылка есть, у лушчего - нет.

2018-12-21 11:06 UTC, vkurennov commented on spec/features/answers/best_spec.rb
> +      within all('.answer').first { expect(page).to have_content "Best answer!" }
Тут есть опасность ложно-положительного теста, т.е. проверка только фразы "Best answer", а не содержимого ответа. Поэтому если лучший ответ здесь не поменялся, а остался тот же, что и был, тест все равно пройдет, потому что в первом ответе есть эта фраза.

2018-12-21 11:06 UTC, vkurennov commented on spec/models/answer_spec.rb
> +      it "check" do
плохое описание. нужно что-то вроде "sets best flag to true"

2018-12-21 11:06 UTC, vkurennov commented on spec/models/answer_spec.rb
> +      it 'un-check' do
а здесь - "sets best flag to false"

2018-12-23 08:26 UTC, neverovda commented on app/views/questions/show.html.slim
> +  = render 'questions/question_show'
У меня уже есть паршал c именем _question, который я использую в index.

2018-12-23 08:49 UTC, neverovda commented on spec/features/answers/best_spec.rb
> +    scenario 'uncheck the best answer', js: true do
Думаю важна ситуация когда 'best' был нажат случайно, или автор передумал; и хочет что бы вопрос остался в статусе не решенного.

2018-12-23 12:34 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  = render 'questions/question_show'
Ок

2018-12-23 12:34 UTC, vkurennov commented on spec/features/answers/best_spec.rb
> +    scenario 'uncheck the best answer', js: true do
Ок

2018-12-23 12:39 UTC, vkurennov requested changes

2018-12-23 12:39 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def author_of_answer?
Особого смысла в методе нет, одна строка заменилась на другую

2018-12-23 12:39 UTC, vkurennov commented on app/models/answer.rb
> +  scope :sorted_by_best_and_created, -> { order(best: :desc, created_at: :asc) }
Лучше покороче названия скоупов придумывать. Можно просто by_best, то что там еще и по created сортировка не так важно

2018-12-23 12:39 UTC, vkurennov commented on app/models/answer.rb
> +  def check_best!
Тут сразу несколько апдейтов, нужно обернуть их в [транзакцию](https://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html)

2018-12-23 12:39 UTC, vkurennov commented on app/models/answer.rb
> +    self.save
Используй тут тоже update, зачем в две строки писать то, что можно в одну?

2018-12-23 12:39 UTC, vkurennov commented on app/models/answer.rb
> +  def check_best!
Учти, что транзакции откатываются только при исключениях, поэтому нужно везде использовать bang-версии методов сохранения/апдейта

2018-12-23 15:09 UTC, vkurennov approved these changes

2018-12-24 01:58 UTC, merged